{
 "title": "Liquibase",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" [1y])) by (deploymentId))"
    }
   ]
  },
  {
   "title": "Dev Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" and liquibaseTargetUrl=~\"(?s).*dev.*\" [1y])) by (deploymentId))"
    }
   ]
  },
  {
   "title": "Test Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" and liquibaseTargetUrl=~\"(?s).*test.*\" [1y])) by (deploymentId))"
    }
   ]
  },
  {
   "title": "Stage Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" and liquibaseTargetUrl=~\"(?s).*stag.*\" [1y])) by (deploymentId))"
    }
   ]
  },
  {
   "title": "Prod Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" and liquibaseTargetUrl=~\"(?s).*prod.*\" [1y])) by (deploymentId))"
    }
   ]
  },
  {
   "title": "Success/Failure Rate (aggregate)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"data\"}  | json | deploymentOutcome = \"failure\" [1y])) / sum(count_over_time({job=\"data\"}  | json | deploymentOutcome = \"failure\" or deploymentOutcome = \"success\" [1y]))) * 100",
     "legendFormat": "Failure"
    },
    {
     "expr": "(sum(count_over_time({job=\"data\"}  | json | deploymentOutcome = \"success\" [1y])) / sum(count_over_time({job=\"data\"}  | json | deploymentOutcome = \"failure\" or deploymentOutcome = \"success\" [1y])) ) * 100",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Success/Failure Rate (aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"data\"} |json | deploymentOutcome=\"failure\"  [1d])) by (deploymentOutcome)",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(count_over_time({job=\"data\"} |json | deploymentOutcome=\"success\"  [1d])) by (deploymentOutcome)",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Releases by Top Apps",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" [1y])) by (commandLabelFilter)",
     "legendFormat": "{{commandLabelFilter}}"
    }
   ]
  },
  {
   "title": "Rollbacks by Apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"data\"} | json | deploymentId!=\"\" and liquibaseCommandName=~\"(?s).*rollback.*\" [1d])) by (deploymentId))",
     "legendFormat": "№ or Rollbacks"
    }
   ]
  },
  {
   "title": "Lead Time to Change",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 26 },
   "targets": [
    {
     "expr": "{job=\"data\"} | json | deploymentId!=\"\" and changesetId!=\"\" and changesetOperationStart!=\"\"  and level=\"INFO\" and liquibaseTargetUrl=~\"(?s).*dev.*\""
    }
   ]
  }
 ]
}