{
 "title": "Liquibase - Cloudwatch",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, deploymentId | filter deploymentId != \"\" | stats count_distinct(deploymentId)",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Test Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, deploymentId | filter deploymentId != \"\" and liquibaseTargetUrl like /test/| stats count_distinct(deploymentId)",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Stage Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, deploymentId | filter deploymentId != \"\" and liquibaseTargetUrl like /stage/| stats count_distinct(deploymentId)",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Dev Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, deploymentId | filter deploymentId != \"\" and liquibaseTargetUrl like /dev/| stats count_distinct(deploymentId)",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Prod Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, deploymentId | filter deploymentId != \"\" and liquibaseTargetUrl like /prod/| stats count_distinct(deploymentId)",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Success/Failure Rate",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\r\n| parse @message /deploymentOutcome[\"\\s]*:[\"\\s]*\"(?<outcome>[^\"]*)/\r\n| filter outcome = \"success\"\r\n| stats count() as Successes",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expression": "fields @timestamp, @message\n| parse @message /deploymentOutcome[\"\\s]*:[\"\\s]*\"(?<outcome>[^\"]*)/\n| filter outcome = \"fail\"\n| stats count() as Failures",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, deploymentId | filter deploymentId != \"\" and liquibaseCommandName like /(?i).*rollback.*/ | stats count_distinct(deploymentId) as rollbackDeployments",
     "logGroups": [
      {
       "accountId": "907240911534",
       "arn": "arn:aws:logs:us-east-1:907240911534:log-group:/aws/lambda/liquibase_get_logs_grafana:*",
       "name": "/aws/lambda/liquibase_get_logs_grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}